### ISSUE TITLE
Disclaimer text overlaps over GitHub logo link

### ISSUE THREAD

**Issue by Icey67** [Icey67/Icey67.github.io---OLD#5]
# Title says all :P
Example screenshots:
![image1](https://github.com/user-attachments/assets/8bb69468-2cc2-43d0-b31a-2652a0b8fc69)
![image2](https://github.com/user-attachments/assets/07329704-6618-4fed-9ccf-bc7b01da9f1d)
![image3](https://github.com/user-attachments/assets/b89049e5-08ae-4715-a5f8-2f804776916d)

## Ways to remedy this:
idk, maybe adjust the font with a media call (text might get unreadable though)
or adjusting the margin may be a good way to fix this

**Comment by eveee00** [comment]
Tbh, it's happening on my site too and I have yet to find a solution.

**Comment by Icey67** [comment]
> and I have jet to find a solution.

![17275309732057202429420514477895](https://github.com/user-attachments/assets/117d020c-4604-4f69-83fd-49ad98b82b44)
"Finding solution..."

**Comment by eveee00** [comment]
fuck i did a typo

**Comment by eveee00** [comment]
btw, i did some experiments on my site, and i think i kinda fixed it.

https://github.com/user-attachments/assets/1a31028f-2545-44f2-8d2d-0e98f3a4089c

the text now moves to the side on mobile devices, i'm gonna mess with it more to see if i can get it to center.

**Comment by eveee00** [comment]
![image](https://github.com/user-attachments/assets/5f5bae4e-f997-4c7d-963a-fe34f91ebe22)
I am such a smart mfer i accidentally pushed to the wrong ~~branch~~ repo.

**Comment by Icey67** [comment]
neat xd
